[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://stayready-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/predict"
  to = "https://stayready-ml-2-0.onrender.com/predict"
  status = 200

[context.production]
  environment = { VITE_ENVIRONMENT = "production" }
